import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { SessionProvider, useSession } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Expense tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="bg-[#1F2937] border-t border-gray-700 w-[100%] px-3 py-2 text-white">
          <Link className="pr-2 " href={"/"}>Home</Link>
          <Link className="pl-2 border-l" href={"/addExp"}>+Add Expense</Link>
        </nav>
        <SessionProvider>{children}</SessionProvider>
        
        
        </body>
    </html>
  );
}
